Update anonsurf

diff --git a/kali-anonsurf-deb-src/etc/init.d/anonsurf b/kali-anonsurf-deb-src/etc/init.d/anonsurf
--- a/kali-anonsurf-deb-src/etc/init.d/anonsurf
+++ b/kali-anonsurf-deb-src/etc/init.d/anonsurf
@@ -64,34 +64,86 @@ function log {
     echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> $LOG_FILE
 }
 
-# Kill switch function
+# Enhanced Kill Switch
 function kill_switch {
+    iptables -F
+    iptables -P INPUT DROP
+    iptables -P OUTPUT DROP
+    iptables -P FORWARD DROP
+    iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
     iptables -A OUTPUT -j DROP
     log "Kill switch activated! All traffic is blocked."
     echo -e "$RED*$BLUE Kill switch activated! All traffic is blocked.$RESETCOLOR"
 }
 
+# DNS Leak Protection
+function dns_leak_protection {
+    iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53
+    iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 53
+    log "DNS leak protection enabled."
+    echo -e "$GREEN*$BLUE DNS leak protection enabled.$RESETCOLOR"
+}
+
+# VPN Integration
+function start_vpn {
+    if [ -f /etc/openvpn/client.conf ]; then
+        openvpn --config /etc/openvpn/client.conf --daemon
+        log "VPN started."
+        echo -e "$GREEN*$BLUE VPN started.$RESETCOLOR"
+    else
+        log "VPN configuration file not found."
+        echo -e "$RED*$BLUE VPN configuration file not found.$RESETCOLOR"
+    fi
+}
+
+function stop_vpn {
+    pkill openvpn
+    log "VPN stopped."
+    echo -e "$GREEN*$BLUE VPN stopped.$RESETCOLOR"
+}
+
+# MAC Address Spoofing
+function spoof_mac {
+    interface=$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo)
+    new_mac=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
+    ip link set dev $interface down
+    ip link set dev $interface address $new_mac
+    ip link set dev $interface up
+    log "MAC address spoofed to $new_mac."
+    echo -e "$GREEN*$BLUE MAC address spoofed to $new_mac.$RESETCOLOR"
+}
+
 # Interactive menu function
 function interactive_menu {
-    echo -e "$GREEN[*] Select an option:$RESETCOLOR"
-    echo -e "1) Start AnonSurf"
-    echo -e "2) Stop AnonSurf"
-    echo -e "3) Change Tor Identity"
-    echo -e "4) Check Status"
-    echo -e "5) Show My IP"
-    echo -e "6) Change IP (Restart Tor)"
-    echo -e "7) Exit"
-    read -p "Choice: " choice
-    case $choice in
-        1) start ;;
-        2) stop ;;
-        3) change ;;
-        4) status ;;
-        5) ip ;;
-        6) changeip ;;
-        7) exit 0 ;;
-        *) echo -e "$RED[*] Invalid choice!$RESETCOLOR" ;;
-    esac
+    while true; do
+        echo -e "$GREEN[*] Select an option:$RESETCOLOR"
+        echo -e "1) Start AnonSurf"
+        echo -e "2) Stop AnonSurf"
+        echo -e "3) Change Tor Identity"
+        echo -e "4) Check Status"
+        echo -e "5) Show My IP"
+        echo -e "6) Change IP (Restart Tor)"
+        echo -e "7) Start VPN"
+        echo -e "8) Stop VPN"
+        echo -e "9) Spoof MAC Address"
+        echo -e "10) Enable DNS Leak Protection"
+        echo -e "11) Exit"
+        read -p "Choice: " choice
+        case $choice in
+            1) start ;;
+            2) stop ;;
+            3) change ;;
+            4) status ;;
+            5) ip ;;
+            6) changeip ;;
+            7) start_vpn ;;
+            8) stop_vpn ;;
+            9) spoof_mac ;;
+            10) dns_leak_protection ;;
+            11) exit 0 ;;
+            *) echo -e "$RED[*] Invalid choice!$RESETCOLOR" ;;
+        esac
+    done
 }
 
 # Function to change IP by restarting Tor
@@ -262,65 +314,52 @@ function start {
     else
         cp /etc/resolvconf/resolv.conf.d/head{,.bak}
         echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head
-        echo -e " $GREEN*$BLUE Modified resolvconf to use localhost and Private Internet Access DNS$RESETCOLOR\n"
+        echo -e " $GREEN*$BLUE Modified resolvconf to use Tor and Private Internet Access DNS$RESETCOLOR\n"
         resolvconf -u
     fi
 
-    # set iptables nat
-    iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
+    # Redirect all traffic through Tor
+    iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
     iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53
     iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 53
-    iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports 53
-    
-    #resolve .onion domains mapping 10.192.0.0/10 address space
-    iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports 9040
-    iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports 9040
-    
-    #exclude local addresses
-    for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10; do
+
+    # Exclude local networks from Tor
+    for NET in $TOR_EXCLUDE; do
         iptables -t nat -A OUTPUT -d $NET -j RETURN
     done
-    
-    #redirect all other output through TOR
+
+    # Allow loopback traffic
+    iptables -t nat -A OUTPUT -o lo -j RETURN
+
+    # Allow Tor process to bypass the rules
+    iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
+
+    # Redirect all other traffic through Tor
     iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
-    iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
-    iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
-    
-    #accept already established connections
+
+    # Block non-Tor traffic
     iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-    
-    #exclude local addresses
-    for NET in $TOR_EXCLUDE 127.0.0.0/8; do
-        iptables -A OUTPUT -d $NET -j ACCEPT
-    done
-    
-    #allow only tor output
     iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
     iptables -A OUTPUT -j REJECT
 
-    echo -e "$GREEN *$BLUE All traffic was redirected through Tor$RESETCOLOR\n"
-    echo -e "$GREEN[$BLUE i$GREEN ]$BLUE You are under AnonSurf tunnel$RESETCOLOR\n"
+    log "AnonSurf started. All traffic is now routed through Tor."
+    echo -e "$GREEN*$BLUE AnonSurf started. All traffic is now routed through Tor.$RESETCOLOR"
 }
 
 function stop {
-    # Make sure only root can run our script
-    if [ $(id -u) -ne 0 ]; then
-        echo -e "\n$GREEN[$RED!$GREEN] $RED This script must be run as root$RESETCOLOR\n" >&2
-        exit 1
-    fi
     echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Stopping anonymous mode:$RESETCOLOR\n"
 
-    iptables -F
-    iptables -t nat -F
-    echo -e " $GREEN*$BLUE Deleted all iptables rules\n$RESETCOLOR"
-    
+    # Restore original iptables rules
     if [ -f /etc/network/iptables.rules ]; then
         iptables-restore < /etc/network/iptables.rules
-        rm /etc/network/iptables.rules
-        echo -e " $GREEN*$BLUE Iptables rules restored"
+        echo -e " $GREEN*$BLUE Restored iptables rules$RESETCOLOR\n"
+    else
+        iptables -F
+        iptables -t nat -F
+        echo -e " $GREEN*$BLUE Flushed iptables rules$RESETCOLOR\n"
     fi
-    
-    # restore DNS settings
+
+    # Restore original DNS settings
     if [ "$resolvconf_support" = false ]; then
         if [ -e /etc/resolv.conf.bak ]; then
             rm /etc/resolv.conf
@@ -330,85 +369,87 @@ function stop {
         mv /etc/resolvconf/resolv.conf.d/head{.bak,}
         resolvconf -u
     fi
-    
-    service tor stop
-    
-    echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Reenabling IPv6 services:$RESETCOLOR\n"
 
-    # reenable IPv6 services
     enable_ipv6
-    
-    echo -e " $GREEN*$BLUE Anonymous mode stopped$RESETCOLOR\n"
+
+    log "AnonSurf stopped. Traffic is no longer routed through Tor."
+    echo -e "$GREEN*$BLUE AnonSurf stopped. Traffic is no longer routed through Tor.$RESETCOLOR"
 }
 
 function change {
-    service tor reload
+    echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Changing Tor identity:$RESETCOLOR\n"
+    killall -HUP tor
     sleep 2
-    echo -e " $GREEN*$BLUE Tor daemon reloaded and forced to change nodes$RESETCOLOR\n"
+    log "Tor identity changed."
+    echo -e "$GREEN*$BLUE Tor identity changed.$RESETCOLOR"
 }
 
 function status {
-    service tor status
+    echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Checking AnonSurf status:$RESETCOLOR\n"
+    if [ -e /var/run/tor/tor.pid ]; then
+        echo -e " $GREEN*$BLUE Tor is running.$RESETCOLOR"
+    else
+        echo -e " $RED*$BLUE Tor is not running.$RESETCOLOR"
+    fi
+
+    iptables -L -v -n | grep -q "owner UID match $TOR_UID"
+    if [ $? -eq 0 ]; then
+        echo -e " $GREEN*$BLUE Traffic is being routed through Tor.$RESETCOLOR"
+    else
+        echo -e " $RED*$BLUE Traffic is not being routed through Tor.$RESETCOLOR"
+    fi
+
+    log "Status checked."
 }
 
+function cleanup {
+    echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Cleaning up:$RESETCOLOR\n"
+    stop
+    rm -f /etc/network/iptables.rules
+    log "Cleanup completed."
+    echo -e "$GREEN*$BLUE Cleanup completed.$RESETCOLOR"
+}
+
+# Main script logic
 case "$1" in
     start)
-        init
         start
-    ;;
+        ;;
     stop)
-        init
         stop
-    ;;
+        ;;
+    restart)
+        stop
+        start
+        ;;
     change)
         change
-    ;;
-    changeip)
-        changeip
-    ;;
+        ;;
     status)
         status
-    ;;
-    myip|ip)
+        ;;
+    ip)
         ip
-    ;;
+        ;;
+    changeip)
+        changeip
+        ;;
     starti2p)
         starti2p
-    ;;
+        ;;
     stopi2p)
         stopi2p
-    ;;
-    restart)
-        $0 stop
-        sleep 1
-        $0 start
-    ;;
-    interactive)
+        ;;
+    menu)
         interactive_menu
-    ;;
+        ;;
+    cleanup)
+        cleanup
+        ;;
     *)
-        echo -e "
-Parrot AnonSurf Module
-    Usage:
-    $RED┌──[$GREEN$USER$YELLOW@$BLUE`hostname`$RED]─[$GREEN$PWD$RED]
-    $RED└──╼ \$$GREEN"" anonsurf $RED{$GREEN""start$RED|$GREEN""stop$RED|$GREEN""restart$RED|$GREEN""change$RED|$GREEN""changeip$RED|$GREEN""status$RED|$GREEN""myip$RED|$GREEN""interactive$RED""}
-    
-    $RED start$BLUE -$GREEN Start system-wide anonymous tunneling under TOR proxy through iptables
-    $RED stop$BLUE -$GREEN Reset original iptables settings and return to clear navigation
-    $RED restart$BLUE -$GREEN Combines \"stop\" and \"start\" options
-    $RED change$BLUE -$GREEN Changes identity by reloading Tor
-    $RED changeip$BLUE -$GREEN Changes IP address by restarting Tor
-    $RED status$BLUE -$GREEN Check if AnonSurf is working properly
-    $RED myip$BLUE -$GREEN Show your current IP address $RED(CHECK)$RESETCOLOR
-    $RED interactive$BLUE -$GREEN Launch interactive menu
-    ----[ I2P related features ]----
-    $RED starti2p$BLUE -$GREEN Start i2p services
-    $RED stopi2p$BLUE -$GREEN Stop i2p services
-    
-$RESETCOLOR" >&2
-    exit 1
-    ;;
+        echo -e "$GREEN[*] Usage: $0 {start|stop|restart|change|status|ip|changeip|starti2p|stopi2p|menu|cleanup}$RESETCOLOR"
+        exit 1
+        ;;
 esac
 
-echo -e $RESETCOLOR
 exit 0
